development:
  database: c9
  adapter: mysql2
  encoding: utf8
  username: <%=ENV['C9_USER']%>
  host: <%=ENV['IP']%>


test:
  database: c9/default
  adapter: mysql2
  encoding: utf8
  username: <%=ENV['C9_USER']%>
  host: <%=ENV['IP']%>

